import {
  Baby,
  Bitcoin,
  Briefcase,
  Car,
  Coffee,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Home,
  LineChart,
  Music,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Target,
  TrendingUp,
  User,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  home: Home,
  zap: Zap,
  wifi: Wifi,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  fuel: Fuel,
  car: Car,
  utensils: Utensils,
  coffee: Coffee,
  film: Film,
  music: Music,
  "gamepad-2": Gamepad2,
  "shopping-bag": ShoppingBag,
  plane: Plane,
  gift: Gift,
  sparkles: Sparkles,
  heart: Heart,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  "line-chart": LineChart,
  bitcoin: Bitcoin,
  wallet: Wallet,
  receipt: Receipt,
  target: Target,
  user: User,
  users: Users,
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  baby: Baby,
  dumbbell: Dumbbell,
  stethoscope: Stethoscope,
  smartphone: Smartphone,
  "paw-print": PawPrint,
};

export const ICON_KEYS = Object.keys(ICONS);

export function getIcon(key: string): LucideIcon {
  return ICONS[key] ?? Wallet;
}
